### ISSUE TITLE
go: cannot find GOROOT directory: /usr/local/go

### ISSUE THREAD

**Issue by AlekSi** [shogo82148/actions-goveralls#214]
When testing with tip version of Go at /usr/local/golang-tip, this action fails with:

```
Run shogo82148/actions-goveralls@v1.4.3
  with:
    path-to-profile: profile.cov
    github-token: ***
    parallel: false
    parallel-finished: false
    job-number: 1
    flag-name: 1
    working-directory: .
/home/runner/work/_actions/shogo82148/actions-goveralls/v1.4.3/bin/goveralls_linux_amd64 -service=github -coverprofile=profile.cov
cannot find file "github.com/qedus/osmpbf/decode.go": can't find "decode.go": go/build: go list github.com/qedus/osmpbf/: exit status 2
go: cannot find GOROOT directory: /usr/local/go
```

There was a similar report at https://github.com/shogo82148/actions-goveralls/issues/178#issuecomment-754252619

See the the full pipeline at https://github.com/qedus/osmpbf/pull/37 (and in the default branch after that PR is merged).
