### ISSUE TITLE
Error using action

### ISSUE THREAD

**Issue by Smolevich** [shogo82148/actions-goveralls#76]
Link failed ci step https://github.com/Smolevich/remark/runs/551483371?check_suite_focus=true

**Comment by shogo82148** [comment]
It looks that you tried to run goverall directly.
Did it work correctly?

>       # - name: submit coverage
>       #   run: $(go env GOPATH)/bin/goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/profile.cov
>       #   working-directory: backend
>       #   env:
>       #     COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

if it is yes, the `working-directory` input is required.

```yaml
      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: ../profile.cov
          working-directory: backend
```
